Add atlas default config
HSF/phoenix pull request #188
Opened 2020-12-04 11:54 UTC by EdwardMoyse

This tries to make the default for ATLAS a bit more useful.

I disabled some jet collections (to stop them overlapping and looking weird) and also some duplicate track collections. I recoloured the Pixel and SCT hits to make them standout a bit more.

As discussed in bug#187 (thanks @9inpachi!) I had to make ngOnInit async and await geometry loading.

2020-12-04 13:57 UTC, 9inpachi requested changes

2020-12-04 13:57 UTC, 9inpachi commented on packages/phoenix-ng/projects/phoenix-ui-components/package.json
> +    "prepublishOnly": "node --eval \"console.error('ERROR: Trying to publish a package that has been compiled by NGCC. This is not allowed.\\nPlease delete and rebuild the package, without compiling
All cool apart from this. :)

2020-12-05 07:18 UTC, EdwardMoyse commented
I think this works now.

2020-12-05 08:35 UTC, 9inpachi approved these changes

2020-12-05 08:35 UTC, 9inpachi commented on packages/phoenix-ng/projects/phoenix-ui-components/package.json
> +    "prepublishOnly": "node --eval \"console.error('ERROR: Trying to publish a package that has been compiled by NGCC. This is not allowed.\\nPlease delete and rebuild the package, without compiling
I meant that you need to discard this file completely (like in the previous PR #186) and not have these changes. For making use of lerna, we have to use this `package.json` for publishing but NGCC blocks that so this file should not be changed at all.

2020-12-05 08:41 UTC, 9inpachi commented
Merging this now and will push with the changes because I think the CI is broken as well.

2020-12-05 08:41 UTC, merged