feat(app): added a checkbox to hide invisible objects in collections
HSF/phoenix pull request #380
Opened 2021-11-27 16:16 UTC by gauravsharma21

With reference to issue #378, I added a checkbox to hide invisible objects in collections

### Preview
![Hnet-image](https://user-images.githubusercontent.com/41608359/143688678-808b1774-7c64-4408-9e5b-8ccf1275e811.gif)

2021-11-28 19:49 UTC, 9inpachi requested changes
Would recommend to place the checkbox below the collection select or right next to it. The way it is now, if the collections info panel has a large width, the checkbox isn't as prominent in terms of UX and can be missed.

2021-11-28 19:49 UTC, 9inpachi commented on packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/collections-info/collections-info-overlay/collections-info-overlay.component.scss
> +    .checkbox-wrapper {
The layout you have can be achieved with flex. No need to use any other properties.

2021-11-28 19:49 UTC, 9inpachi commented on packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/collections-info/collections-info-overlay/collections-info-overlay.component.html
> +        <mat-checkbox (change)="toggleInvisible($event.checked)">
No need for a wrapper here. Once you use flex the right way, the item will become right aligned.

2021-11-28 19:49 UTC, 9inpachi commented on packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/collections-info/collections-info-overlay/collections-info-overlay.component.html
>        class="collectionSelector mb-2 d-flex align-items-center"
Use this wrapper to achieve the current layout you have using bootstrap's flex related classes.

2021-11-28 19:49 UTC, 9inpachi commented on packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/collections-info/collections-info-overlay/collections-info-overlay.component.ts
> +  hideInvisible: boolean;
Just having this `hideInvisible` for keeping the checkbox value is enough. No need to make any other changes to the component code, you could just use the `isCut` of an object property to decide whether to display a row or not.

2021-11-30 13:51 UTC, 9inpachi requested changes

2021-11-30 13:51 UTC, 9inpachi commented on packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/collections-info/collections-info-overlay/collections-info-overlay.component.html
> +              hide: object.isCut && hideInvisible
Bootstrap already has a class for this: `d-none`.

2021-11-30 13:51 UTC, 9inpachi commented on packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/collections-info/collections-info-overlay/collections-info-overlay.component.html
> +        <div class="checkbox-wrapper" *ngIf="showingCollection">
This wrapper looks redundant to me. I am not sure but does the layout not work without this?

2021-11-30 13:51 UTC, 9inpachi commented on packages/phoenix-ng/projects/phoenix-ui-components/src/components/ui-menu/collections-info/collections-info-overlay/collections-info-overlay.component.scss
> +      color: var(--phoenix-text-color-secondary);
It should pick up the primary color automatically. which should be fine.

2021-11-30 14:18 UTC, gauravsharma21 commented
![image](https://user-images.githubusercontent.com/41608359/144063749-028efbe1-b8fb-44c3-a7ff-440528374241.png)

@9inpachi Is this fine or should I add some margin between the dropdown & checkbox?

2021-11-30 14:42 UTC, EdwardMoyse commented
> ![image](https://user-images.githubusercontent.com/41608359/144063749-028efbe1-b8fb-44c3-a7ff-440528374241.png)
> 
> @9inpachi Is this fine or should I add some margin between the dropdown & checkbox?

I think some margin would look better.

2021-11-30 16:28 UTC, 9inpachi approved these changes
Thanks a lot!

2021-11-30 16:28 UTC, merged